;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        andrew-org-space
        asm-colon
        auto-complete-self-insert
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-command
        cperl-electric-backspace
        cperl-electric-brace
        cperl-electric-lbrace
        cperl-electric-paren
        cperl-electric-rparen
        cperl-electric-semi
        cperl-indent-command
        cua-copy-region
        cua-delete-region
        cua-paste
        cua-scroll-up
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        electric-newline-and-maybe-indent
        fill-paragraph
        forward-sentence
        indent-for-tab-command
        jump-to-matching-paren
        kill-sentence
        org-beginning-of-line
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-kill-line
        org-self-insert-command
        overwrite-mode
        sh-end-of-command
        tcl-electric-brace
        tcl-electric-char
        tcl-electric-hash
        tcl-indent-command
        ))

(setq mc/cmds-to-run-once
      '(
        about-emacs
        asm-comment
        handle-switch-frame
        mouse-set-region
        sh-assignment
        ))
