;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        andrew-org-space
        asm-colon
        auto-complete-self-insert
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-command
        cperl-electric-backspace
        cperl-electric-paren
        cperl-electric-rparen
        cperl-electric-semi
        cperl-indent-command
        delete-horizontal-space
        electric-newline-and-maybe-indent
        indent-for-tab-command
        jump-to-matching-paren
        kill-sentence
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-self-insert-command
        overwrite-mode
        tcl-electric-hash
        ))

(setq mc/cmds-to-run-once
      '(
        asm-comment
        handle-switch-frame
        sh-assignment
        ))
